name: PR Reviews Reminder

on:
  schedule:
    - cron: '* * * * 1-5'

jobs:
  pr-reviews-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Review Badger
        uses: nicklemmon/review-badger@v0.0.16-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          slackChannel: '#pr-review-bot'
